# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5dd4af60056f42640ae4833226cf6accd74458943792c6d37062bd139c292e423bb2a2c5bebc58e43f0bf318b6343473c5f74dbd7aceec988c9d55

test:
  secret_key_base: 202347d4896f18e9c16a30dfe18a021eb735ce44535ba176516515baa55a02afdb3b79b58a06de739b94c362a66d88e2ee2d776b6c616a5cbce9309a6628f698

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
